#EasyStaffList by Gareth Swan

title: 'insert here'
owner: 'insert here'
coowner: 'insert here'
headdev: 'insert here'
dev: 'insert here'
headadmin: 'insert here'
admin: 'insert here'
headmod: 'insert here'
mod: 'insert here'
builder: 'insert here'
author: 'HumaneBending Head Developer - Gareth Swan'

#If you want anything edited such as staff ranks added,
#changed or removed, then just message me on my Bukkit
#or Spigot Forum at
#http://bit.ly/Bukkit-Swan
#http://bit.ly/Spigot-Swan
#or email me at > gareth_swan@outlook.com
#or discord message me > GarethSwan#8953

#Thank you for using EasyStaffList!

 